import type { DictEntry } from './types';

export const java: DictEntry[] = [
  // ---- String / StringBuilder methods ----
  { label: 'length', kind: 'method', signature: 'str.length()', doc: 'Return the string length (arrays use the .length property, no parentheses)', insertText: 'length()$0' },
  { label: 'charAt', kind: 'method', signature: 'str.charAt(index)', doc: 'Return the character at the given position', insertText: 'charAt($0)' },
  { label: 'substring', kind: 'method', signature: 'str.substring(begin, end)', doc: 'Return the substring [begin, end)', insertText: 'substring($0)' },
  { label: 'indexOf', kind: 'method', signature: 'str.indexOf(str)', doc: 'Return the index of the first occurrence of a substring, or -1 if not found', insertText: 'indexOf($0)' },
  { label: 'toCharArray', kind: 'method', signature: 'str.toCharArray()', doc: 'Convert the string to a character array', insertText: 'toCharArray()$0' },
  { label: 'equals', kind: 'method', signature: 'obj.equals(other)', doc: 'Check whether two objects are equal in content', insertText: 'equals($0)' },
  { label: 'compareTo', kind: 'method', signature: 'str.compareTo(other)', doc: 'Compare two strings lexicographically', insertText: 'compareTo($0)' },
  { label: 'split', kind: 'method', signature: 'str.split(regex)', doc: 'Split a string using a regular expression', insertText: 'split($0)' },
  { label: 'trim', kind: 'method', signature: 'str.trim()', doc: 'Remove leading and trailing whitespace from the string', insertText: 'trim()$0' },
  { label: 'toLowerCase', kind: 'method', signature: 'str.toLowerCase()', doc: 'Convert to lowercase', insertText: 'toLowerCase()$0' },
  { label: 'toUpperCase', kind: 'method', signature: 'str.toUpperCase()', doc: 'Convert to uppercase', insertText: 'toUpperCase()$0' },
  { label: 'contains', kind: 'method', signature: 'str.contains(sub)', doc: 'Check whether a subsequence is contained', insertText: 'contains($0)' },
  { label: 'isEmpty', kind: 'method', signature: 'str.isEmpty()', doc: 'Check whether the string/collection is empty', insertText: 'isEmpty()$0' },
  { label: 'valueOf', kind: 'function', signature: 'String.valueOf(x)', doc: 'Convert another type to a string', insertText: 'valueOf($0)' },
  { label: 'parseInt', kind: 'function', signature: 'Integer.parseInt(str)', doc: 'Parse a string into an int', insertText: 'parseInt($0)' },
  { label: 'toString', kind: 'method', signature: 'obj.toString()', doc: 'Return a string representation of the object', insertText: 'toString()$0' },
  { label: 'append', kind: 'method', signature: 'sb.append(x)', doc: 'Append content to the end of a StringBuilder', insertText: 'append($0)' },
  { label: 'reverse', kind: 'method', signature: 'sb.reverse()', doc: 'Reverse the character sequence in a StringBuilder', insertText: 'reverse()$0' },
  { label: 'deleteCharAt', kind: 'method', signature: 'sb.deleteCharAt(index)', doc: 'Delete the character at the given position', insertText: 'deleteCharAt($0)' },
  { label: 'setCharAt', kind: 'method', signature: 'sb.setCharAt(index, ch)', doc: 'Set the character at the given position', insertText: 'setCharAt($1, $0)' },

  // ---- Collection / Map / Deque methods ----
  { label: 'add', kind: 'method', signature: 'list.add(x)', doc: 'Add an element to a collection/list', insertText: 'add($0)' },
  { label: 'remove', kind: 'method', signature: 'list.remove(x)', doc: 'Remove an element (by index for List, by value for Collection)', insertText: 'remove($0)' },
  { label: 'get', kind: 'method', signature: 'list.get(index)', doc: 'Get an element by index/key (List or Map)', insertText: 'get($0)' },
  { label: 'set', kind: 'method', signature: 'list.set(index, x)', doc: 'Set the element at the given index', insertText: 'set($1, $0)' },
  { label: 'size', kind: 'method', signature: 'collection.size()', doc: 'Return the number of elements in the collection', insertText: 'size()$0' },
  { label: 'put', kind: 'method', signature: 'map.put(key, value)', doc: 'Insert or update a key-value pair in the Map', insertText: 'put($1, $0)' },
  { label: 'getOrDefault', kind: 'method', signature: 'map.getOrDefault(key, default)', doc: 'Look up a value by key, returning a default if not present', insertText: 'getOrDefault($1, $0)' },
  { label: 'containsKey', kind: 'method', signature: 'map.containsKey(key)', doc: 'Check whether the Map contains the given key', insertText: 'containsKey($0)' },
  { label: 'containsValue', kind: 'method', signature: 'map.containsValue(value)', doc: 'Check whether the Map contains the given value', insertText: 'containsValue($0)' },
  { label: 'keySet', kind: 'method', signature: 'map.keySet()', doc: 'Return a Set view of all keys in the Map', insertText: 'keySet()$0' },
  { label: 'entrySet', kind: 'method', signature: 'map.entrySet()', doc: 'Return a Set view of all key-value pairs in the Map', insertText: 'entrySet()$0' },
  { label: 'putIfAbsent', kind: 'method', signature: 'map.putIfAbsent(key, value)', doc: 'Insert only if the key is not already present', insertText: 'putIfAbsent($1, $0)' },
  { label: 'merge', kind: 'method', signature: 'map.merge(key, value, function)', doc: 'Merge a value into the key, computing a new value via the function if the key exists', insertText: 'merge($1, $2, $0)' },
  { label: 'offer', kind: 'method', signature: 'queue.offer(x)', doc: 'Add an element to the end of the queue', insertText: 'offer($0)' },
  { label: 'poll', kind: 'method', signature: 'queue.poll()', doc: 'Remove and return the head of the queue, or null if empty', insertText: 'poll()$0' },
  { label: 'peek', kind: 'method', signature: 'queue.peek()', doc: 'Return the head of the queue without removing it, or null if empty', insertText: 'peek()$0' },
  { label: 'push', kind: 'method', signature: 'deque.push(x)', doc: 'Push an element onto the top of the stack (head of the Deque)', insertText: 'push($0)' },
  { label: 'addFirst', kind: 'method', signature: 'deque.addFirst(x)', doc: 'Add an element to the head of the deque', insertText: 'addFirst($0)' },
  { label: 'addLast', kind: 'method', signature: 'deque.addLast(x)', doc: 'Add an element to the tail of the deque', insertText: 'addLast($0)' },
  { label: 'pollFirst', kind: 'method', signature: 'deque.pollFirst()', doc: 'Remove and return the head element of the deque', insertText: 'pollFirst()$0' },
  { label: 'pollLast', kind: 'method', signature: 'deque.pollLast()', doc: 'Remove and return the tail element of the deque', insertText: 'pollLast()$0' },

  // ---- Arrays / Collections / Math ----
  { label: 'sort', kind: 'method', signature: 'Arrays.sort(arr)', doc: 'Sort an array or list', insertText: 'sort($0)' },
  { label: 'fill', kind: 'function', signature: 'Arrays.fill(arr, value)', doc: 'Fill an array with the given value', insertText: 'fill($1, $0)' },
  { label: 'copyOf', kind: 'function', signature: 'Arrays.copyOf(arr, newLength)', doc: 'Copy an array to the given length', insertText: 'copyOf($1, $0)' },
  { label: 'copyOfRange', kind: 'function', signature: 'Arrays.copyOfRange(arr, from, to)', doc: 'Copy the given range [from, to) of an array', insertText: 'copyOfRange($1, $2, $0)' },
  { label: 'binarySearch', kind: 'function', signature: 'Arrays.binarySearch(arr, key)', doc: 'Binary search a sorted array', insertText: 'binarySearch($1, $0)' },
  { label: 'asList', kind: 'function', signature: 'Arrays.asList(elements)', doc: 'Wrap an array as a fixed-size List', insertText: 'asList($0)' },
  { label: 'swap', kind: 'function', signature: 'Collections.swap(list, i, j)', doc: 'Swap the elements at two positions in a list', insertText: 'swap($1, $2, $0)' },
  { label: 'max', kind: 'function', signature: 'Math.max(a, b)', doc: 'Return the larger value', insertText: 'max($1, $0)' },
  { label: 'min', kind: 'function', signature: 'Math.min(a, b)', doc: 'Return the smaller value', insertText: 'min($1, $0)' },
  { label: 'abs', kind: 'function', signature: 'Math.abs(x)', doc: 'Return the absolute value', insertText: 'abs($0)' },
  { label: 'sqrt', kind: 'function', signature: 'Math.sqrt(x)', doc: 'Return the square root', insertText: 'sqrt($0)' },
  { label: 'pow', kind: 'function', signature: 'Math.pow(base, exp)', doc: 'Return the result of exponentiation', insertText: 'pow($1, $0)' },
  { label: 'floor', kind: 'function', signature: 'Math.floor(x)', doc: 'Round down to the nearest integer', insertText: 'floor($0)' },
  { label: 'ceil', kind: 'function', signature: 'Math.ceil(x)', doc: 'Round up to the nearest integer', insertText: 'ceil($0)' },

  // ---- keywords / types ----
  { label: 'public', kind: 'keyword', signature: 'public', doc: 'Public access modifier', insertText: 'public' },
  { label: 'private', kind: 'keyword', signature: 'private', doc: 'Private access modifier', insertText: 'private' },
  { label: 'static', kind: 'keyword', signature: 'static', doc: 'Static member modifier', insertText: 'static' },
  { label: 'final', kind: 'keyword', signature: 'final', doc: 'Modifier for immutable/non-inheritable declarations', insertText: 'final' },
  { label: 'void', kind: 'keyword', signature: 'void', doc: 'No-return-value type', insertText: 'void' },
  { label: 'int', kind: 'keyword', signature: 'int', doc: '32-bit integer type', insertText: 'int' },
  { label: 'long', kind: 'keyword', signature: 'long', doc: '64-bit integer type', insertText: 'long' },
  { label: 'char', kind: 'keyword', signature: 'char', doc: 'Single-character type', insertText: 'char' },
  { label: 'boolean', kind: 'keyword', signature: 'boolean', doc: 'Boolean type', insertText: 'boolean' },
  { label: 'double', kind: 'keyword', signature: 'double', doc: 'Double-precision floating-point type', insertText: 'double' },
  { label: 'String', kind: 'class', signature: 'String', doc: 'String type', insertText: 'String' },
  { label: 'new', kind: 'keyword', signature: 'new ClassName(args)', doc: 'Create a new object instance', insertText: 'new' },
  { label: 'return', kind: 'keyword', signature: 'return expr;', doc: 'Return a value from a method', insertText: 'return' },
  { label: 'if', kind: 'keyword', signature: 'if (condition) {}', doc: 'Conditional branch', insertText: 'if (${1:condition}) {\n    $0\n}' },
  { label: 'else', kind: 'keyword', signature: 'else {}', doc: 'Default branch of a conditional', insertText: 'else {\n    $0\n}' },
  { label: 'for', kind: 'keyword', signature: 'for (init; cond; step) {}', doc: 'Classic for loop', insertText: 'for (int ${1:i} = 0; ${1:i} < ${2:n}; ${1:i}++) {\n    $0\n}' },
  { label: 'while', kind: 'keyword', signature: 'while (condition) {}', doc: 'Conditional loop', insertText: 'while (${1:condition}) {\n    $0\n}' },
  { label: 'break', kind: 'keyword', signature: 'break;', doc: 'Break out of the current loop/switch', insertText: 'break' },
  { label: 'continue', kind: 'keyword', signature: 'continue;', doc: 'Skip the rest of the current loop iteration', insertText: 'continue' },
  { label: 'class', kind: 'keyword', signature: 'class Name {}', doc: 'Define a class', insertText: 'class ${1:Name} {\n    $0\n}' },
  { label: 'extends', kind: 'keyword', signature: 'class A extends B', doc: 'Extend a parent class', insertText: 'extends' },
  { label: 'implements', kind: 'keyword', signature: 'class A implements B', doc: 'Implement an interface', insertText: 'implements' },
  { label: 'null', kind: 'keyword', signature: 'null', doc: 'Null reference constant', insertText: 'null' },
  { label: 'true', kind: 'keyword', signature: 'true', doc: 'Boolean true value', insertText: 'true' },
  { label: 'false', kind: 'keyword', signature: 'false', doc: 'Boolean false value', insertText: 'false' },

  // ---- common classes ----
  { label: 'ArrayList', kind: 'class', signature: 'ArrayList<E>', doc: 'Resizable list backed by an array', insertText: 'ArrayList<$0>' },
  { label: 'HashMap', kind: 'class', signature: 'HashMap<K, V>', doc: 'Key-value map backed by a hash table', insertText: 'HashMap<$1, $0>' },
  { label: 'HashSet', kind: 'class', signature: 'HashSet<E>', doc: 'Unordered set backed by a hash table', insertText: 'HashSet<$0>' },
  { label: 'LinkedList', kind: 'class', signature: 'LinkedList<E>', doc: 'Doubly linked list implementing both List and Deque', insertText: 'LinkedList<$0>' },
  { label: 'ArrayDeque', kind: 'class', signature: 'ArrayDeque<E>', doc: 'Double-ended queue backed by an array', insertText: 'ArrayDeque<$0>' },
  { label: 'PriorityQueue', kind: 'class', signature: 'PriorityQueue<E>', doc: 'Priority queue backed by a heap, min-heap by default', insertText: 'PriorityQueue<$0>' },
  { label: 'TreeMap', kind: 'class', signature: 'TreeMap<K, V>', doc: 'Sorted key-value map backed by a red-black tree', insertText: 'TreeMap<$1, $0>' },
  { label: 'TreeSet', kind: 'class', signature: 'TreeSet<E>', doc: 'Sorted set backed by a red-black tree', insertText: 'TreeSet<$0>' },
  { label: 'StringBuilder', kind: 'class', signature: 'StringBuilder', doc: 'Mutable character sequence for efficient string concatenation', insertText: 'StringBuilder($0)' },
  { label: 'Arrays', kind: 'class', signature: 'java.util.Arrays', doc: 'Utility class for array operations', insertText: 'Arrays' },
  { label: 'Collections', kind: 'class', signature: 'java.util.Collections', doc: 'Utility class for collection operations', insertText: 'Collections' },
  { label: 'Math', kind: 'class', signature: 'java.lang.Math', doc: 'Utility class for math functions', insertText: 'Math' },
  { label: 'Integer', kind: 'class', signature: 'java.lang.Integer', doc: 'Wrapper class for int', insertText: 'Integer' },
  { label: 'Character', kind: 'class', signature: 'java.lang.Character', doc: 'Wrapper class for char', insertText: 'Character' },
  { label: 'Comparator', kind: 'class', signature: 'Comparator<T>', doc: 'Comparator interface, commonly used for custom sort order', insertText: 'Comparator<$0>' },
];
