import type { DictEntry } from './types';

export const java: DictEntry[] = [
  // ---- String / StringBuilder 方法 ----
  { label: 'length', kind: 'method', signature: 'str.length()', doc: '返回字符串长度（数组用 .length 属性，不带括号）', insertText: 'length()$0' },
  { label: 'charAt', kind: 'method', signature: 'str.charAt(index)', doc: '返回指定位置的字符', insertText: 'charAt($0)' },
  { label: 'substring', kind: 'method', signature: 'str.substring(begin, end)', doc: '返回子字符串 [begin, end)', insertText: 'substring($0)' },
  { label: 'indexOf', kind: 'method', signature: 'str.indexOf(str)', doc: '返回子串首次出现的下标，找不到返回 -1', insertText: 'indexOf($0)' },
  { label: 'toCharArray', kind: 'method', signature: 'str.toCharArray()', doc: '将字符串转换为字符数组', insertText: 'toCharArray()$0' },
  { label: 'equals', kind: 'method', signature: 'obj.equals(other)', doc: '判断两个对象内容是否相等', insertText: 'equals($0)' },
  { label: 'compareTo', kind: 'method', signature: 'str.compareTo(other)', doc: '按字典序比较两个字符串', insertText: 'compareTo($0)' },
  { label: 'split', kind: 'method', signature: 'str.split(regex)', doc: '按正则表达式切分字符串', insertText: 'split($0)' },
  { label: 'trim', kind: 'method', signature: 'str.trim()', doc: '去除字符串首尾空白', insertText: 'trim()$0' },
  { label: 'toLowerCase', kind: 'method', signature: 'str.toLowerCase()', doc: '转换为小写', insertText: 'toLowerCase()$0' },
  { label: 'toUpperCase', kind: 'method', signature: 'str.toUpperCase()', doc: '转换为大写', insertText: 'toUpperCase()$0' },
  { label: 'contains', kind: 'method', signature: 'str.contains(sub)', doc: '判断是否包含子序列', insertText: 'contains($0)' },
  { label: 'isEmpty', kind: 'method', signature: 'str.isEmpty()', doc: '判断字符串/集合是否为空', insertText: 'isEmpty()$0' },
  { label: 'valueOf', kind: 'function', signature: 'String.valueOf(x)', doc: '将其他类型转换为字符串', insertText: 'valueOf($0)' },
  { label: 'parseInt', kind: 'function', signature: 'Integer.parseInt(str)', doc: '将字符串解析为 int', insertText: 'parseInt($0)' },
  { label: 'toString', kind: 'method', signature: 'obj.toString()', doc: '返回对象的字符串表示', insertText: 'toString()$0' },
  { label: 'append', kind: 'method', signature: 'sb.append(x)', doc: '向 StringBuilder 末尾追加内容', insertText: 'append($0)' },
  { label: 'reverse', kind: 'method', signature: 'sb.reverse()', doc: '反转 StringBuilder 中的字符序列', insertText: 'reverse()$0' },
  { label: 'deleteCharAt', kind: 'method', signature: 'sb.deleteCharAt(index)', doc: '删除指定位置的字符', insertText: 'deleteCharAt($0)' },
  { label: 'setCharAt', kind: 'method', signature: 'sb.setCharAt(index, ch)', doc: '设置指定位置的字符', insertText: 'setCharAt($1, $0)' },

  // ---- Collection / Map / Deque 方法 ----
  { label: 'add', kind: 'method', signature: 'list.add(x)', doc: '向集合/列表添加元素', insertText: 'add($0)' },
  { label: 'remove', kind: 'method', signature: 'list.remove(x)', doc: '删除元素（List 按下标，Collection 按值）', insertText: 'remove($0)' },
  { label: 'get', kind: 'method', signature: 'list.get(index)', doc: '按下标/键获取元素（List 或 Map）', insertText: 'get($0)' },
  { label: 'set', kind: 'method', signature: 'list.set(index, x)', doc: '设置指定下标处的元素', insertText: 'set($1, $0)' },
  { label: 'size', kind: 'method', signature: 'collection.size()', doc: '返回集合中元素的个数', insertText: 'size()$0' },
  { label: 'put', kind: 'method', signature: 'map.put(key, value)', doc: '向 Map 中插入或更新键值对', insertText: 'put($1, $0)' },
  { label: 'getOrDefault', kind: 'method', signature: 'map.getOrDefault(key, default)', doc: '按键取值，不存在时返回默认值', insertText: 'getOrDefault($1, $0)' },
  { label: 'containsKey', kind: 'method', signature: 'map.containsKey(key)', doc: '判断 Map 是否包含指定键', insertText: 'containsKey($0)' },
  { label: 'containsValue', kind: 'method', signature: 'map.containsValue(value)', doc: '判断 Map 是否包含指定值', insertText: 'containsValue($0)' },
  { label: 'keySet', kind: 'method', signature: 'map.keySet()', doc: '返回 Map 所有键组成的 Set 视图', insertText: 'keySet()$0' },
  { label: 'entrySet', kind: 'method', signature: 'map.entrySet()', doc: '返回 Map 所有键值对组成的 Set 视图', insertText: 'entrySet()$0' },
  { label: 'putIfAbsent', kind: 'method', signature: 'map.putIfAbsent(key, value)', doc: '键不存在时才插入', insertText: 'putIfAbsent($1, $0)' },
  { label: 'merge', kind: 'method', signature: 'map.merge(key, value, function)', doc: '合并键值，键存在时用函数计算新值', insertText: 'merge($1, $2, $0)' },
  { label: 'offer', kind: 'method', signature: 'queue.offer(x)', doc: '向队列末尾添加元素', insertText: 'offer($0)' },
  { label: 'poll', kind: 'method', signature: 'queue.poll()', doc: '弹出并返回队首元素，队空返回 null', insertText: 'poll()$0' },
  { label: 'peek', kind: 'method', signature: 'queue.peek()', doc: '返回队首元素但不移除，队空返回 null', insertText: 'peek()$0' },
  { label: 'push', kind: 'method', signature: 'deque.push(x)', doc: '将元素压入栈顶（Deque 头部）', insertText: 'push($0)' },
  { label: 'addFirst', kind: 'method', signature: 'deque.addFirst(x)', doc: '在双端队列头部添加元素', insertText: 'addFirst($0)' },
  { label: 'addLast', kind: 'method', signature: 'deque.addLast(x)', doc: '在双端队列尾部添加元素', insertText: 'addLast($0)' },
  { label: 'pollFirst', kind: 'method', signature: 'deque.pollFirst()', doc: '弹出并返回双端队列头部元素', insertText: 'pollFirst()$0' },
  { label: 'pollLast', kind: 'method', signature: 'deque.pollLast()', doc: '弹出并返回双端队列尾部元素', insertText: 'pollLast()$0' },

  // ---- Arrays / Collections / Math ----
  { label: 'sort', kind: 'method', signature: 'Arrays.sort(arr)', doc: '对数组或列表排序', insertText: 'sort($0)' },
  { label: 'fill', kind: 'function', signature: 'Arrays.fill(arr, value)', doc: '用指定值填充数组', insertText: 'fill($1, $0)' },
  { label: 'copyOf', kind: 'function', signature: 'Arrays.copyOf(arr, newLength)', doc: '复制数组到指定长度', insertText: 'copyOf($1, $0)' },
  { label: 'copyOfRange', kind: 'function', signature: 'Arrays.copyOfRange(arr, from, to)', doc: '复制数组的指定区间 [from, to)', insertText: 'copyOfRange($1, $2, $0)' },
  { label: 'binarySearch', kind: 'function', signature: 'Arrays.binarySearch(arr, key)', doc: '在有序数组中二分查找', insertText: 'binarySearch($1, $0)' },
  { label: 'asList', kind: 'function', signature: 'Arrays.asList(elements)', doc: '将数组包装为固定大小的 List', insertText: 'asList($0)' },
  { label: 'swap', kind: 'function', signature: 'Collections.swap(list, i, j)', doc: '交换列表中两个位置的元素', insertText: 'swap($1, $2, $0)' },
  { label: 'max', kind: 'function', signature: 'Math.max(a, b)', doc: '返回较大值', insertText: 'max($1, $0)' },
  { label: 'min', kind: 'function', signature: 'Math.min(a, b)', doc: '返回较小值', insertText: 'min($1, $0)' },
  { label: 'abs', kind: 'function', signature: 'Math.abs(x)', doc: '返回绝对值', insertText: 'abs($0)' },
  { label: 'sqrt', kind: 'function', signature: 'Math.sqrt(x)', doc: '返回平方根', insertText: 'sqrt($0)' },
  { label: 'pow', kind: 'function', signature: 'Math.pow(base, exp)', doc: '返回幂运算结果', insertText: 'pow($1, $0)' },
  { label: 'floor', kind: 'function', signature: 'Math.floor(x)', doc: '向下取整', insertText: 'floor($0)' },
  { label: 'ceil', kind: 'function', signature: 'Math.ceil(x)', doc: '向上取整', insertText: 'ceil($0)' },

  // ---- 关键字 / 类型 ----
  { label: 'public', kind: 'keyword', signature: 'public', doc: '公开访问修饰符', insertText: 'public' },
  { label: 'private', kind: 'keyword', signature: 'private', doc: '私有访问修饰符', insertText: 'private' },
  { label: 'static', kind: 'keyword', signature: 'static', doc: '静态成员修饰符', insertText: 'static' },
  { label: 'final', kind: 'keyword', signature: 'final', doc: '不可变/不可继承修饰符', insertText: 'final' },
  { label: 'void', kind: 'keyword', signature: 'void', doc: '无返回值类型', insertText: 'void' },
  { label: 'int', kind: 'keyword', signature: 'int', doc: '32 位整数类型', insertText: 'int' },
  { label: 'long', kind: 'keyword', signature: 'long', doc: '64 位整数类型', insertText: 'long' },
  { label: 'char', kind: 'keyword', signature: 'char', doc: '单字符类型', insertText: 'char' },
  { label: 'boolean', kind: 'keyword', signature: 'boolean', doc: '布尔类型', insertText: 'boolean' },
  { label: 'double', kind: 'keyword', signature: 'double', doc: '双精度浮点类型', insertText: 'double' },
  { label: 'String', kind: 'class', signature: 'String', doc: '字符串类型', insertText: 'String' },
  { label: 'new', kind: 'keyword', signature: 'new ClassName(args)', doc: '创建对象实例', insertText: 'new' },
  { label: 'return', kind: 'keyword', signature: 'return expr;', doc: '从方法返回值', insertText: 'return' },
  { label: 'if', kind: 'keyword', signature: 'if (condition) {}', doc: '条件分支', insertText: 'if (${1:condition}) {\n    $0\n}' },
  { label: 'else', kind: 'keyword', signature: 'else {}', doc: '条件分支的默认分支', insertText: 'else {\n    $0\n}' },
  { label: 'for', kind: 'keyword', signature: 'for (init; cond; step) {}', doc: '经典 for 循环', insertText: 'for (int ${1:i} = 0; ${1:i} < ${2:n}; ${1:i}++) {\n    $0\n}' },
  { label: 'while', kind: 'keyword', signature: 'while (condition) {}', doc: '条件循环', insertText: 'while (${1:condition}) {\n    $0\n}' },
  { label: 'break', kind: 'keyword', signature: 'break;', doc: '跳出当前循环/switch', insertText: 'break' },
  { label: 'continue', kind: 'keyword', signature: 'continue;', doc: '跳过本次循环剩余部分', insertText: 'continue' },
  { label: 'class', kind: 'keyword', signature: 'class Name {}', doc: '定义类', insertText: 'class ${1:Name} {\n    $0\n}' },
  { label: 'extends', kind: 'keyword', signature: 'class A extends B', doc: '继承父类', insertText: 'extends' },
  { label: 'implements', kind: 'keyword', signature: 'class A implements B', doc: '实现接口', insertText: 'implements' },
  { label: 'null', kind: 'keyword', signature: 'null', doc: '空引用常量', insertText: 'null' },
  { label: 'true', kind: 'keyword', signature: 'true', doc: '布尔真值', insertText: 'true' },
  { label: 'false', kind: 'keyword', signature: 'false', doc: '布尔假值', insertText: 'false' },

  // ---- 常用类 ----
  { label: 'ArrayList', kind: 'class', signature: 'ArrayList<E>', doc: '基于数组实现的可变长列表', insertText: 'ArrayList<$0>' },
  { label: 'HashMap', kind: 'class', signature: 'HashMap<K, V>', doc: '基于哈希表实现的键值映射', insertText: 'HashMap<$1, $0>' },
  { label: 'HashSet', kind: 'class', signature: 'HashSet<E>', doc: '基于哈希表实现的无序集合', insertText: 'HashSet<$0>' },
  { label: 'LinkedList', kind: 'class', signature: 'LinkedList<E>', doc: '双向链表，实现 List 和 Deque', insertText: 'LinkedList<$0>' },
  { label: 'ArrayDeque', kind: 'class', signature: 'ArrayDeque<E>', doc: '基于数组实现的双端队列', insertText: 'ArrayDeque<$0>' },
  { label: 'PriorityQueue', kind: 'class', signature: 'PriorityQueue<E>', doc: '基于堆实现的优先队列，默认小顶堆', insertText: 'PriorityQueue<$0>' },
  { label: 'TreeMap', kind: 'class', signature: 'TreeMap<K, V>', doc: '基于红黑树实现的有序键值映射', insertText: 'TreeMap<$1, $0>' },
  { label: 'TreeSet', kind: 'class', signature: 'TreeSet<E>', doc: '基于红黑树实现的有序集合', insertText: 'TreeSet<$0>' },
  { label: 'StringBuilder', kind: 'class', signature: 'StringBuilder', doc: '可变字符序列，用于高效拼接字符串', insertText: 'StringBuilder($0)' },
  { label: 'Arrays', kind: 'class', signature: 'java.util.Arrays', doc: '数组操作工具类', insertText: 'Arrays' },
  { label: 'Collections', kind: 'class', signature: 'java.util.Collections', doc: '集合操作工具类', insertText: 'Collections' },
  { label: 'Math', kind: 'class', signature: 'java.lang.Math', doc: '数学函数工具类', insertText: 'Math' },
  { label: 'Integer', kind: 'class', signature: 'java.lang.Integer', doc: 'int 的包装类', insertText: 'Integer' },
  { label: 'Character', kind: 'class', signature: 'java.lang.Character', doc: 'char 的包装类', insertText: 'Character' },
  { label: 'Comparator', kind: 'class', signature: 'Comparator<T>', doc: '比较器接口，常用于自定义排序', insertText: 'Comparator<$0>' },
];
