import type { DictEntry } from './types';

export const javascript: DictEntry[] = [
  // ---- Array 方法 ----
  { label: 'push', kind: 'method', signature: 'arr.push(item)', doc: '在数组末尾添加一个或多个元素', insertText: 'push($0)' },
  { label: 'pop', kind: 'method', signature: 'arr.pop()', doc: '删除并返回数组最后一个元素', insertText: 'pop()$0' },
  { label: 'shift', kind: 'method', signature: 'arr.shift()', doc: '删除并返回数组第一个元素', insertText: 'shift()$0' },
  { label: 'unshift', kind: 'method', signature: 'arr.unshift(item)', doc: '在数组开头添加一个或多个元素', insertText: 'unshift($0)' },
  { label: 'slice', kind: 'method', signature: 'arr.slice(start, end)', doc: '返回数组/字符串的浅拷贝片段', insertText: 'slice($0)' },
  { label: 'splice', kind: 'method', signature: 'arr.splice(start, deleteCount, items)', doc: '删除/插入数组元素并修改原数组', insertText: 'splice($0)' },
  { label: 'sort', kind: 'method', signature: 'arr.sort(compareFn)', doc: '原地对数组排序', insertText: 'sort($0)' },
  { label: 'reverse', kind: 'method', signature: 'arr.reverse()', doc: '原地反转数组', insertText: 'reverse()$0' },
  { label: 'map', kind: 'method', signature: 'arr.map(fn)', doc: '对每个元素应用函数并返回新数组', insertText: 'map($0)' },
  { label: 'filter', kind: 'method', signature: 'arr.filter(fn)', doc: '返回满足条件的元素组成的新数组', insertText: 'filter($0)' },
  { label: 'reduce', kind: 'method', signature: 'arr.reduce(fn, init)', doc: '将数组归约为单一值', insertText: 'reduce($0)' },
  { label: 'forEach', kind: 'method', signature: 'arr.forEach(fn)', doc: '对每个元素执行函数，无返回值', insertText: 'forEach($0)' },
  { label: 'find', kind: 'method', signature: 'arr.find(fn)', doc: '返回第一个满足条件的元素', insertText: 'find($0)' },
  { label: 'findIndex', kind: 'method', signature: 'arr.findIndex(fn)', doc: '返回第一个满足条件的元素下标', insertText: 'findIndex($0)' },
  { label: 'includes', kind: 'method', signature: 'arr.includes(value)', doc: '判断数组/字符串是否包含指定值', insertText: 'includes($0)' },
  { label: 'indexOf', kind: 'method', signature: 'arr.indexOf(value)', doc: '返回值首次出现的下标，找不到返回 -1', insertText: 'indexOf($0)' },
  { label: 'join', kind: 'method', signature: 'arr.join(sep)', doc: '将数组元素拼接为字符串', insertText: 'join($0)' },
  { label: 'concat', kind: 'method', signature: 'arr.concat(other)', doc: '合并数组并返回新数组', insertText: 'concat($0)' },
  { label: 'flat', kind: 'method', signature: 'arr.flat(depth)', doc: '按指定深度展平嵌套数组', insertText: 'flat($0)' },
  { label: 'fill', kind: 'method', signature: 'arr.fill(value, start, end)', doc: '用指定值填充数组', insertText: 'fill($0)' },
  { label: 'some', kind: 'method', signature: 'arr.some(fn)', doc: '判断是否存在满足条件的元素', insertText: 'some($0)' },
  { label: 'every', kind: 'method', signature: 'arr.every(fn)', doc: '判断是否所有元素都满足条件', insertText: 'every($0)' },
  { label: 'from', kind: 'function', signature: 'Array.from(arrayLike, mapFn)', doc: '从类数组或可迭代对象创建数组', insertText: 'from($0)' },
  { label: 'isArray', kind: 'function', signature: 'Array.isArray(value)', doc: '判断值是否为数组', insertText: 'isArray($0)' },
  { label: 'keys', kind: 'method', signature: 'map.keys()', doc: '返回键的迭代器（Map/Set/Array 实例方法；普通对象请用 Object.keys(obj)）', insertText: 'keys()$0' },
  { label: 'values', kind: 'method', signature: 'map.values()', doc: '返回值的迭代器（Map/Set/Array 实例方法；普通对象请用 Object.values(obj)）', insertText: 'values()$0' },
  { label: 'entries', kind: 'method', signature: 'map.entries()', doc: '返回 [key, value] 对的迭代器（Map/Array 实例方法；普通对象请用 Object.entries(obj)）', insertText: 'entries()$0' },

  // ---- String 方法 ----
  { label: 'split', kind: 'method', signature: 'str.split(sep)', doc: '按分隔符切分字符串为数组', insertText: 'split($0)' },
  { label: 'trim', kind: 'method', signature: 'str.trim()', doc: '去除字符串首尾空白', insertText: 'trim()$0' },
  { label: 'toLowerCase', kind: 'method', signature: 'str.toLowerCase()', doc: '转换为小写', insertText: 'toLowerCase()$0' },
  { label: 'toUpperCase', kind: 'method', signature: 'str.toUpperCase()', doc: '转换为大写', insertText: 'toUpperCase()$0' },
  { label: 'charAt', kind: 'method', signature: 'str.charAt(index)', doc: '返回指定位置的字符', insertText: 'charAt($0)' },
  { label: 'charCodeAt', kind: 'method', signature: 'str.charCodeAt(index)', doc: '返回指定位置字符的 UTF-16 编码', insertText: 'charCodeAt($0)' },
  { label: 'fromCharCode', kind: 'function', signature: 'String.fromCharCode(code)', doc: '根据编码返回对应字符', insertText: 'fromCharCode($0)' },
  { label: 'substring', kind: 'method', signature: 'str.substring(start, end)', doc: '返回字符串子串 [start, end)', insertText: 'substring($0)' },
  { label: 'repeat', kind: 'method', signature: 'str.repeat(count)', doc: '将字符串重复指定次数', insertText: 'repeat($0)' },
  { label: 'padStart', kind: 'method', signature: 'str.padStart(targetLength, padString)', doc: '在字符串开头填充至目标长度', insertText: 'padStart($0)' },
  { label: 'replace', kind: 'method', signature: 'str.replace(pattern, replacement)', doc: '替换匹配到的子串（首个或按正则）', insertText: 'replace($1, $0)' },
  { label: 'startsWith', kind: 'method', signature: 'str.startsWith(prefix)', doc: '判断字符串是否以 prefix 开头', insertText: 'startsWith($0)' },
  { label: 'endsWith', kind: 'method', signature: 'str.endsWith(suffix)', doc: '判断字符串是否以 suffix 结尾', insertText: 'endsWith($0)' },

  // ---- Map/Set 方法 ----
  { label: 'get', kind: 'method', signature: 'map.get(key)', doc: '按键获取 Map 中的值', insertText: 'get($0)' },
  { label: 'set', kind: 'method', signature: 'map.set(key, value)', doc: '设置 Map 中的键值对', insertText: 'set($1, $0)' },
  { label: 'has', kind: 'method', signature: 'map.has(key)', doc: '判断 Map/Set 是否包含指定键或值', insertText: 'has($0)' },
  { label: 'delete', kind: 'method', signature: 'map.delete(key)', doc: '删除 Map/Set 中指定的键或值', insertText: 'delete($0)' },
  { label: 'add', kind: 'method', signature: 'set.add(value)', doc: '向 Set 添加元素', insertText: 'add($0)' },
  { label: 'size', kind: 'method', signature: 'map.size', doc: 'Map/Set 中元素的个数（属性，非方法）', insertText: 'size' },

  // ---- Math ----
  { label: 'max', kind: 'function', signature: 'Math.max(a, b)', doc: '返回较大值', insertText: 'max($0)' },
  { label: 'min', kind: 'function', signature: 'Math.min(a, b)', doc: '返回较小值', insertText: 'min($0)' },
  { label: 'abs', kind: 'function', signature: 'Math.abs(x)', doc: '返回绝对值', insertText: 'abs($0)' },
  { label: 'floor', kind: 'function', signature: 'Math.floor(x)', doc: '向下取整', insertText: 'floor($0)' },
  { label: 'ceil', kind: 'function', signature: 'Math.ceil(x)', doc: '向上取整', insertText: 'ceil($0)' },
  { label: 'sqrt', kind: 'function', signature: 'Math.sqrt(x)', doc: '返回平方根', insertText: 'sqrt($0)' },
  { label: 'pow', kind: 'function', signature: 'Math.pow(base, exp)', doc: '返回幂运算结果', insertText: 'pow($1, $0)' },
  { label: 'round', kind: 'function', signature: 'Math.round(x)', doc: '四舍五入到最近整数', insertText: 'round($0)' },
  { label: 'sign', kind: 'function', signature: 'Math.sign(x)', doc: '返回数值的符号（1、-1 或 0）', insertText: 'sign($0)' },
  { label: 'Infinity', kind: 'constant', signature: 'Infinity', doc: '表示正无穷大的全局常量', insertText: 'Infinity' },

  // ---- 关键字 ----
  { label: 'const', kind: 'keyword', signature: 'const name = value;', doc: '声明块级作用域常量', insertText: 'const' },
  { label: 'let', kind: 'keyword', signature: 'let name = value;', doc: '声明块级作用域变量', insertText: 'let' },
  { label: 'function', kind: 'keyword', signature: 'function name(args) {}', doc: '定义函数', insertText: 'function ${1:name}(${2:args}) {\n    $0\n}' },
  { label: 'return', kind: 'keyword', signature: 'return expr;', doc: '从函数返回值', insertText: 'return' },
  { label: 'if', kind: 'keyword', signature: 'if (condition) {}', doc: '条件分支', insertText: 'if (${1:condition}) {\n    $0\n}' },
  { label: 'else', kind: 'keyword', signature: 'else {}', doc: '条件分支的默认分支', insertText: 'else {\n    $0\n}' },
  { label: 'for', kind: 'keyword', signature: 'for (init; cond; step) {}', doc: '经典 for 循环', insertText: 'for (let ${1:i} = 0; ${1:i} < ${2:n}; ${1:i}++) {\n    $0\n}' },
  { label: 'while', kind: 'keyword', signature: 'while (condition) {}', doc: '条件循环', insertText: 'while (${1:condition}) {\n    $0\n}' },
  { label: 'of', kind: 'keyword', signature: 'for (const x of iterable) {}', doc: '按值遍历可迭代对象', insertText: 'of' },
  { label: 'in', kind: 'keyword', signature: 'for (const key in obj) {}', doc: '遍历对象可枚举属性名', insertText: 'in' },
  { label: 'new', kind: 'keyword', signature: 'new ClassName(args)', doc: '创建对象实例', insertText: 'new' },
  { label: 'class', kind: 'keyword', signature: 'class Name {}', doc: '定义类', insertText: 'class ${1:Name} {\n    $0\n}' },
  { label: 'null', kind: 'keyword', signature: 'null', doc: '表示空值', insertText: 'null' },
  { label: 'undefined', kind: 'keyword', signature: 'undefined', doc: '表示未定义', insertText: 'undefined' },
  { label: 'true', kind: 'keyword', signature: 'true', doc: '布尔真值', insertText: 'true' },
  { label: 'false', kind: 'keyword', signature: 'false', doc: '布尔假值', insertText: 'false' },
  { label: 'typeof', kind: 'keyword', signature: 'typeof x', doc: '返回操作数的类型字符串', insertText: 'typeof' },
  { label: 'break', kind: 'keyword', signature: 'break;', doc: '跳出当前循环/switch', insertText: 'break' },
  { label: 'continue', kind: 'keyword', signature: 'continue;', doc: '跳过本次循环剩余部分', insertText: 'continue' },

  // ---- 常用类/对象 ----
  { label: 'Map', kind: 'class', signature: 'new Map()', doc: '键值对集合，键可为任意类型', insertText: 'new Map()$0' },
  { label: 'Set', kind: 'class', signature: 'new Set()', doc: '值的集合，元素唯一', insertText: 'new Set()$0' },
  { label: 'Array', kind: 'class', signature: 'new Array(length)', doc: '数组构造函数', insertText: 'Array($0)' },
  { label: 'Number', kind: 'class', signature: 'Number(value)', doc: '将值转换为数字，或作为数字工具类', insertText: 'Number($0)' },
  { label: 'JSON', kind: 'module', signature: 'JSON', doc: '提供 parse/stringify 的内置对象', insertText: 'JSON' },
  { label: 'parseInt', kind: 'function', signature: 'parseInt(str, radix)', doc: '将字符串解析为整数', insertText: 'parseInt($0)' },
  { label: 'parseFloat', kind: 'function', signature: 'parseFloat(str)', doc: '将字符串解析为浮点数', insertText: 'parseFloat($0)' },

  // ---- 少量额外常用项 ----
  { label: 'MAX_SAFE_INTEGER', kind: 'constant', signature: 'Number.MAX_SAFE_INTEGER', doc: 'JS 中可安全表示的最大整数', insertText: 'MAX_SAFE_INTEGER' },
  { label: 'MIN_SAFE_INTEGER', kind: 'constant', signature: 'Number.MIN_SAFE_INTEGER', doc: 'JS 中可安全表示的最小整数', insertText: 'MIN_SAFE_INTEGER' },
];
