import type { DictEntry } from './types';

export const javascript: DictEntry[] = [
  // ---- Array methods ----
  { label: 'push', kind: 'method', signature: 'arr.push(item)', doc: 'Add one or more elements to the end of the array', insertText: 'push($0)' },
  { label: 'pop', kind: 'method', signature: 'arr.pop()', doc: 'Remove and return the last element of the array', insertText: 'pop()$0' },
  { label: 'shift', kind: 'method', signature: 'arr.shift()', doc: 'Remove and return the first element of the array', insertText: 'shift()$0' },
  { label: 'unshift', kind: 'method', signature: 'arr.unshift(item)', doc: 'Add one or more elements to the start of the array', insertText: 'unshift($0)' },
  { label: 'slice', kind: 'method', signature: 'arr.slice(start, end)', doc: 'Return a shallow copy of a portion of the array/string', insertText: 'slice($0)' },
  { label: 'splice', kind: 'method', signature: 'arr.splice(start, deleteCount, items)', doc: 'Remove/insert array elements, mutating the original array', insertText: 'splice($0)' },
  { label: 'sort', kind: 'method', signature: 'arr.sort(compareFn)', doc: 'Sort the array in place', insertText: 'sort($0)' },
  { label: 'reverse', kind: 'method', signature: 'arr.reverse()', doc: 'Reverse the array in place', insertText: 'reverse()$0' },
  { label: 'map', kind: 'method', signature: 'arr.map(fn)', doc: 'Apply a function to each element and return a new array', insertText: 'map($0)' },
  { label: 'filter', kind: 'method', signature: 'arr.filter(fn)', doc: 'Return a new array of elements that satisfy a condition', insertText: 'filter($0)' },
  { label: 'reduce', kind: 'method', signature: 'arr.reduce(fn, init)', doc: 'Reduce the array to a single value', insertText: 'reduce($0)' },
  { label: 'forEach', kind: 'method', signature: 'arr.forEach(fn)', doc: 'Execute a function for each element, with no return value', insertText: 'forEach($0)' },
  { label: 'find', kind: 'method', signature: 'arr.find(fn)', doc: 'Return the first element that satisfies a condition', insertText: 'find($0)' },
  { label: 'findIndex', kind: 'method', signature: 'arr.findIndex(fn)', doc: 'Return the index of the first element that satisfies a condition', insertText: 'findIndex($0)' },
  { label: 'includes', kind: 'method', signature: 'arr.includes(value)', doc: 'Check whether the array/string contains the given value', insertText: 'includes($0)' },
  { label: 'indexOf', kind: 'method', signature: 'arr.indexOf(value)', doc: 'Return the index of the first occurrence of a value, or -1 if not found', insertText: 'indexOf($0)' },
  { label: 'join', kind: 'method', signature: 'arr.join(sep)', doc: 'Join array elements into a string', insertText: 'join($0)' },
  { label: 'concat', kind: 'method', signature: 'arr.concat(other)', doc: 'Merge arrays and return a new array', insertText: 'concat($0)' },
  { label: 'flat', kind: 'method', signature: 'arr.flat(depth)', doc: 'Flatten nested arrays to the given depth', insertText: 'flat($0)' },
  { label: 'fill', kind: 'method', signature: 'arr.fill(value, start, end)', doc: 'Fill the array with the given value', insertText: 'fill($0)' },
  { label: 'some', kind: 'method', signature: 'arr.some(fn)', doc: 'Check whether any element satisfies a condition', insertText: 'some($0)' },
  { label: 'every', kind: 'method', signature: 'arr.every(fn)', doc: 'Check whether all elements satisfy a condition', insertText: 'every($0)' },
  { label: 'from', kind: 'function', signature: 'Array.from(arrayLike, mapFn)', doc: 'Create an array from an array-like or iterable object', insertText: 'from($0)' },
  { label: 'isArray', kind: 'function', signature: 'Array.isArray(value)', doc: 'Check whether a value is an array', insertText: 'isArray($0)' },
  { label: 'keys', kind: 'method', signature: 'map.keys()', doc: 'Return an iterator of keys (Map/Set/Array instance method; use Object.keys(obj) for plain objects)', insertText: 'keys()$0' },
  { label: 'values', kind: 'method', signature: 'map.values()', doc: 'Return an iterator of values (Map/Set/Array instance method; use Object.values(obj) for plain objects)', insertText: 'values()$0' },
  { label: 'entries', kind: 'method', signature: 'map.entries()', doc: 'Return an iterator of [key, value] pairs (Map/Array instance method; use Object.entries(obj) for plain objects)', insertText: 'entries()$0' },

  // ---- String methods ----
  { label: 'split', kind: 'method', signature: 'str.split(sep)', doc: 'Split a string into an array using a separator', insertText: 'split($0)' },
  { label: 'trim', kind: 'method', signature: 'str.trim()', doc: 'Remove leading and trailing whitespace', insertText: 'trim()$0' },
  { label: 'toLowerCase', kind: 'method', signature: 'str.toLowerCase()', doc: 'Convert to lowercase', insertText: 'toLowerCase()$0' },
  { label: 'toUpperCase', kind: 'method', signature: 'str.toUpperCase()', doc: 'Convert to uppercase', insertText: 'toUpperCase()$0' },
  { label: 'charAt', kind: 'method', signature: 'str.charAt(index)', doc: 'Return the character at the given position', insertText: 'charAt($0)' },
  { label: 'charCodeAt', kind: 'method', signature: 'str.charCodeAt(index)', doc: 'Return the UTF-16 code of the character at the given position', insertText: 'charCodeAt($0)' },
  { label: 'fromCharCode', kind: 'function', signature: 'String.fromCharCode(code)', doc: 'Return the character corresponding to a code', insertText: 'fromCharCode($0)' },
  { label: 'substring', kind: 'method', signature: 'str.substring(start, end)', doc: 'Return the substring [start, end)', insertText: 'substring($0)' },
  { label: 'repeat', kind: 'method', signature: 'str.repeat(count)', doc: 'Repeat the string the given number of times', insertText: 'repeat($0)' },
  { label: 'padStart', kind: 'method', signature: 'str.padStart(targetLength, padString)', doc: 'Pad the start of the string to reach the target length', insertText: 'padStart($0)' },
  { label: 'replace', kind: 'method', signature: 'str.replace(pattern, replacement)', doc: 'Replace a matched substring (first match, or by regex)', insertText: 'replace($1, $0)' },
  { label: 'startsWith', kind: 'method', signature: 'str.startsWith(prefix)', doc: 'Check whether the string starts with prefix', insertText: 'startsWith($0)' },
  { label: 'endsWith', kind: 'method', signature: 'str.endsWith(suffix)', doc: 'Check whether the string ends with suffix', insertText: 'endsWith($0)' },

  // ---- Map/Set methods ----
  { label: 'get', kind: 'method', signature: 'map.get(key)', doc: 'Get a value from a Map by key', insertText: 'get($0)' },
  { label: 'set', kind: 'method', signature: 'map.set(key, value)', doc: 'Set a key-value pair in a Map', insertText: 'set($1, $0)' },
  { label: 'has', kind: 'method', signature: 'map.has(key)', doc: 'Check whether a Map/Set contains the given key or value', insertText: 'has($0)' },
  { label: 'delete', kind: 'method', signature: 'map.delete(key)', doc: 'Delete the given key or value from a Map/Set', insertText: 'delete($0)' },
  { label: 'add', kind: 'method', signature: 'set.add(value)', doc: 'Add an element to a Set', insertText: 'add($0)' },
  { label: 'size', kind: 'method', signature: 'map.size', doc: 'Number of elements in a Map/Set (property, not a method)', insertText: 'size' },

  // ---- Math ----
  { label: 'max', kind: 'function', signature: 'Math.max(a, b)', doc: 'Return the larger value', insertText: 'max($0)' },
  { label: 'min', kind: 'function', signature: 'Math.min(a, b)', doc: 'Return the smaller value', insertText: 'min($0)' },
  { label: 'abs', kind: 'function', signature: 'Math.abs(x)', doc: 'Return the absolute value', insertText: 'abs($0)' },
  { label: 'floor', kind: 'function', signature: 'Math.floor(x)', doc: 'Round down to the nearest integer', insertText: 'floor($0)' },
  { label: 'ceil', kind: 'function', signature: 'Math.ceil(x)', doc: 'Round up to the nearest integer', insertText: 'ceil($0)' },
  { label: 'sqrt', kind: 'function', signature: 'Math.sqrt(x)', doc: 'Return the square root', insertText: 'sqrt($0)' },
  { label: 'pow', kind: 'function', signature: 'Math.pow(base, exp)', doc: 'Return the result of exponentiation', insertText: 'pow($1, $0)' },
  { label: 'round', kind: 'function', signature: 'Math.round(x)', doc: 'Round to the nearest integer', insertText: 'round($0)' },
  { label: 'sign', kind: 'function', signature: 'Math.sign(x)', doc: 'Return the sign of a number (1, -1, or 0)', insertText: 'sign($0)' },
  { label: 'Infinity', kind: 'constant', signature: 'Infinity', doc: 'Global constant representing positive infinity', insertText: 'Infinity' },

  // ---- keywords ----
  { label: 'const', kind: 'keyword', signature: 'const name = value;', doc: 'Declare a block-scoped constant', insertText: 'const' },
  { label: 'let', kind: 'keyword', signature: 'let name = value;', doc: 'Declare a block-scoped variable', insertText: 'let' },
  { label: 'function', kind: 'keyword', signature: 'function name(args) {}', doc: 'Define a function', insertText: 'function ${1:name}(${2:args}) {\n    $0\n}' },
  { label: 'return', kind: 'keyword', signature: 'return expr;', doc: 'Return a value from a function', insertText: 'return' },
  { label: 'if', kind: 'keyword', signature: 'if (condition) {}', doc: 'Conditional branch', insertText: 'if (${1:condition}) {\n    $0\n}' },
  { label: 'else', kind: 'keyword', signature: 'else {}', doc: 'Default branch of a conditional', insertText: 'else {\n    $0\n}' },
  { label: 'for', kind: 'keyword', signature: 'for (init; cond; step) {}', doc: 'Classic for loop', insertText: 'for (let ${1:i} = 0; ${1:i} < ${2:n}; ${1:i}++) {\n    $0\n}' },
  { label: 'while', kind: 'keyword', signature: 'while (condition) {}', doc: 'Conditional loop', insertText: 'while (${1:condition}) {\n    $0\n}' },
  { label: 'of', kind: 'keyword', signature: 'for (const x of iterable) {}', doc: 'Iterate over the values of an iterable', insertText: 'of' },
  { label: 'in', kind: 'keyword', signature: 'for (const key in obj) {}', doc: 'Iterate over the enumerable property names of an object', insertText: 'in' },
  { label: 'new', kind: 'keyword', signature: 'new ClassName(args)', doc: 'Create a new object instance', insertText: 'new' },
  { label: 'class', kind: 'keyword', signature: 'class Name {}', doc: 'Define a class', insertText: 'class ${1:Name} {\n    $0\n}' },
  { label: 'null', kind: 'keyword', signature: 'null', doc: 'Represents an empty value', insertText: 'null' },
  { label: 'undefined', kind: 'keyword', signature: 'undefined', doc: 'Represents an undefined value', insertText: 'undefined' },
  { label: 'true', kind: 'keyword', signature: 'true', doc: 'Boolean true value', insertText: 'true' },
  { label: 'false', kind: 'keyword', signature: 'false', doc: 'Boolean false value', insertText: 'false' },
  { label: 'typeof', kind: 'keyword', signature: 'typeof x', doc: 'Return a string indicating the type of the operand', insertText: 'typeof' },
  { label: 'break', kind: 'keyword', signature: 'break;', doc: 'Break out of the current loop/switch', insertText: 'break' },
  { label: 'continue', kind: 'keyword', signature: 'continue;', doc: 'Skip the rest of the current loop iteration', insertText: 'continue' },

  // ---- common classes/objects ----
  { label: 'Map', kind: 'class', signature: 'new Map()', doc: 'Collection of key-value pairs, keys can be of any type', insertText: 'new Map()$0' },
  { label: 'Set', kind: 'class', signature: 'new Set()', doc: 'Collection of unique values', insertText: 'new Set()$0' },
  { label: 'Array', kind: 'class', signature: 'new Array(length)', doc: 'Array constructor', insertText: 'Array($0)' },
  { label: 'Number', kind: 'class', signature: 'Number(value)', doc: 'Convert a value to a number, or use as a number utility class', insertText: 'Number($0)' },
  { label: 'JSON', kind: 'module', signature: 'JSON', doc: 'Built-in object providing parse/stringify', insertText: 'JSON' },
  { label: 'parseInt', kind: 'function', signature: 'parseInt(str, radix)', doc: 'Parse a string into an integer', insertText: 'parseInt($0)' },
  { label: 'parseFloat', kind: 'function', signature: 'parseFloat(str)', doc: 'Parse a string into a floating-point number', insertText: 'parseFloat($0)' },

  // ---- a few extra common items ----
  { label: 'MAX_SAFE_INTEGER', kind: 'constant', signature: 'Number.MAX_SAFE_INTEGER', doc: 'The largest integer that can be safely represented in JS', insertText: 'MAX_SAFE_INTEGER' },
  { label: 'MIN_SAFE_INTEGER', kind: 'constant', signature: 'Number.MIN_SAFE_INTEGER', doc: 'The smallest integer that can be safely represented in JS', insertText: 'MIN_SAFE_INTEGER' },
];
