import type { DictEntry } from './types';

export const python: DictEntry[] = [
  // ---- list methods ----
  { label: 'append', kind: 'method', signature: 'list.append(x)', doc: 'Append an element to the end of the list', insertText: 'append($0)' },
  { label: 'pop', kind: 'method', signature: 'list.pop(i=-1)', doc: 'Remove and return the element at the given position (default: the last one)', insertText: 'pop($0)' },
  { label: 'sort', kind: 'method', signature: 'list.sort(key=None, reverse=False)', doc: 'Sort the list in place', insertText: 'sort($0)' },
  { label: 'sorted', kind: 'function', signature: 'sorted(iterable, key=None, reverse=False)', doc: 'Return a new sorted list', insertText: 'sorted($0)' },
  { label: 'reverse', kind: 'method', signature: 'list.reverse()', doc: 'Reverse the list in place', insertText: 'reverse()$0' },
  { label: 'insert', kind: 'method', signature: 'list.insert(i, x)', doc: 'Insert an element at the given position', insertText: 'insert($1, $0)' },
  { label: 'remove', kind: 'method', signature: 'list.remove(x)', doc: 'Remove the first element equal to x', insertText: 'remove($0)' },
  { label: 'index', kind: 'method', signature: 'list.index(x)', doc: 'Return the index of the first occurrence of x, raising an exception if not found', insertText: 'index($0)' },
  { label: 'count', kind: 'method', signature: 'list.count(x)', doc: 'Count occurrences of x (works on both list and str)', insertText: 'count($0)' },

  // ---- str methods ----
  { label: 'join', kind: 'method', signature: 'sep.join(iterable)', doc: 'Join a sequence of strings using a separator', insertText: 'join($0)' },
  { label: 'split', kind: 'method', signature: 'str.split(sep=None)', doc: 'Split a string into a list using a separator', insertText: 'split($0)' },
  { label: 'strip', kind: 'method', signature: 'str.strip(chars=None)', doc: 'Remove leading and trailing whitespace (or specified characters)', insertText: 'strip()$0' },
  { label: 'lower', kind: 'method', signature: 'str.lower()', doc: 'Convert to lowercase', insertText: 'lower()$0' },
  { label: 'upper', kind: 'method', signature: 'str.upper()', doc: 'Convert to uppercase', insertText: 'upper()$0' },
  { label: 'startswith', kind: 'method', signature: 'str.startswith(prefix)', doc: 'Check whether the string starts with prefix', insertText: 'startswith($0)' },
  { label: 'endswith', kind: 'method', signature: 'str.endswith(suffix)', doc: 'Check whether the string ends with suffix', insertText: 'endswith($0)' },
  { label: 'replace', kind: 'method', signature: 'str.replace(old, new)', doc: 'Replace all occurrences of old with new in the string', insertText: 'replace($1, $0)' },
  { label: 'find', kind: 'method', signature: 'str.find(sub)', doc: 'Return the index of the first occurrence of a substring, or -1 if not found', insertText: 'find($0)' },
  { label: 'isdigit', kind: 'method', signature: 'str.isdigit()', doc: 'Check whether the string consists only of digit characters', insertText: 'isdigit()$0' },
  { label: 'isalpha', kind: 'method', signature: 'str.isalpha()', doc: 'Check whether the string consists only of alphabetic characters', insertText: 'isalpha()$0' },
  { label: 'ord', kind: 'function', signature: 'ord(c)', doc: 'Return the Unicode code point of a single character', insertText: 'ord($0)' },
  { label: 'chr', kind: 'function', signature: 'chr(i)', doc: 'Return the character corresponding to code point i', insertText: 'chr($0)' },

  // ---- dict/set methods ----
  { label: 'get', kind: 'method', signature: 'dict.get(key, default=None)', doc: 'Look up a value by key, returning default if not present', insertText: 'get($0)' },
  { label: 'keys', kind: 'method', signature: 'dict.keys()', doc: 'Return a view of all keys in the dict', insertText: 'keys()$0' },
  { label: 'values', kind: 'method', signature: 'dict.values()', doc: 'Return a view of all values in the dict', insertText: 'values()$0' },
  { label: 'items', kind: 'method', signature: 'dict.items()', doc: 'Return a view of all key-value pairs in the dict', insertText: 'items()$0' },
  { label: 'setdefault', kind: 'method', signature: 'dict.setdefault(key, default=None)', doc: 'Return the value if key exists, otherwise set it to default and return that', insertText: 'setdefault($1, $0)' },
  { label: 'add', kind: 'method', signature: 'set.add(x)', doc: 'Add an element to the set', insertText: 'add($0)' },
  { label: 'discard', kind: 'method', signature: 'set.discard(x)', doc: 'Remove an element from the set, no error if absent', insertText: 'discard($0)' },
  { label: 'update', kind: 'method', signature: 'set.update(iterable)', doc: 'Update the set (or dict) with elements from an iterable', insertText: 'update($0)' },

  // ---- builtins ----
  { label: 'len', kind: 'function', signature: 'len(obj)', doc: 'Return the length of an object', insertText: 'len($0)' },
  { label: 'range', kind: 'function', signature: 'range(start, stop, step=1)', doc: 'Generate a sequence of integers', insertText: 'range($0)' },
  { label: 'enumerate', kind: 'function', signature: 'enumerate(iterable, start=0)', doc: 'Return an iterator of (index, value) pairs', insertText: 'enumerate($0)' },
  { label: 'zip', kind: 'function', signature: 'zip(*iterables)', doc: 'Pack multiple iterables together in parallel', insertText: 'zip($0)' },
  { label: 'map', kind: 'function', signature: 'map(func, iterable)', doc: 'Apply a function to each item of an iterable', insertText: 'map($1, $0)' },
  { label: 'filter', kind: 'function', signature: 'filter(func, iterable)', doc: 'Filter elements for which the function returns true', insertText: 'filter($1, $0)' },
  { label: 'sum', kind: 'function', signature: 'sum(iterable, start=0)', doc: 'Sum the values', insertText: 'sum($0)' },
  { label: 'min', kind: 'function', signature: 'min(iterable)', doc: 'Return the minimum value', insertText: 'min($0)' },
  { label: 'max', kind: 'function', signature: 'max(iterable)', doc: 'Return the maximum value', insertText: 'max($0)' },
  { label: 'abs', kind: 'function', signature: 'abs(x)', doc: 'Return the absolute value', insertText: 'abs($0)' },
  { label: 'all', kind: 'function', signature: 'all(iterable)', doc: 'Return True if all elements are truthy', insertText: 'all($0)' },
  { label: 'any', kind: 'function', signature: 'any(iterable)', doc: 'Return True if any element is truthy', insertText: 'any($0)' },
  { label: 'set', kind: 'class', signature: 'set(iterable=())', doc: 'Create a set', insertText: 'set($0)' },
  { label: 'dict', kind: 'class', signature: 'dict(**kwargs)', doc: 'Create a dict', insertText: 'dict($0)' },
  { label: 'list', kind: 'class', signature: 'list(iterable=())', doc: 'Create a list', insertText: 'list($0)' },
  { label: 'tuple', kind: 'class', signature: 'tuple(iterable=())', doc: 'Create a tuple', insertText: 'tuple($0)' },
  { label: 'str', kind: 'class', signature: 'str(object=\'\')', doc: 'Convert to a string', insertText: 'str($0)' },
  { label: 'int', kind: 'class', signature: 'int(x=0, base=10)', doc: 'Convert to an integer', insertText: 'int($0)' },
  { label: 'float', kind: 'class', signature: 'float(x=0.0)', doc: 'Convert to a floating-point number', insertText: 'float($0)' },
  { label: 'bool', kind: 'class', signature: 'bool(x=False)', doc: 'Convert to a boolean', insertText: 'bool($0)' },
  { label: 'print', kind: 'function', signature: 'print(*objects, sep=\' \', end=\'\\n\')', doc: 'Print output', insertText: 'print($0)' },
  { label: 'reversed', kind: 'function', signature: 'reversed(sequence)', doc: 'Return a reverse iterator', insertText: 'reversed($0)' },
  { label: 'isinstance', kind: 'function', signature: 'isinstance(obj, classinfo)', doc: 'Check whether an object is an instance of the given type', insertText: 'isinstance($1, $0)' },
  { label: 'divmod', kind: 'function', signature: 'divmod(a, b)', doc: 'Return a tuple of quotient and remainder', insertText: 'divmod($1, $0)' },
  { label: 'pow', kind: 'function', signature: 'pow(base, exp, mod=None)', doc: 'Compute a power (optionally modulo mod)', insertText: 'pow($1, $0)' },
  { label: 'round', kind: 'function', signature: 'round(number, ndigits=None)', doc: 'Round to the given precision', insertText: 'round($0)' },

  // ---- modules ----
  { label: 'heapq', kind: 'module', signature: 'import heapq', doc: 'Heap queue (min-heap) algorithm module', insertText: 'heapq' },
  { label: 'heappush', kind: 'function', signature: 'heapq.heappush(heap, item)', doc: 'Push an element onto the min-heap', insertText: 'heappush($1, $0)' },
  { label: 'heappop', kind: 'function', signature: 'heapq.heappop(heap)', doc: 'Pop and return the smallest element from the heap', insertText: 'heappop($0)' },
  { label: 'heapify', kind: 'function', signature: 'heapq.heapify(x)', doc: 'Transform a list into a heap in place', insertText: 'heapify($0)' },
  { label: 'Counter', kind: 'class', signature: 'collections.Counter(iterable)', doc: 'Counting dict that tracks how often each element occurs', insertText: 'Counter($0)' },
  { label: 'defaultdict', kind: 'class', signature: 'collections.defaultdict(default_factory)', doc: 'Dict with a default-value factory for missing keys', insertText: 'defaultdict($0)' },
  { label: 'deque', kind: 'class', signature: 'collections.deque(iterable=())', doc: 'Double-ended queue', insertText: 'deque($0)' },
  { label: 'popleft', kind: 'method', signature: 'deque.popleft()', doc: 'Pop and return the leftmost element of the deque', insertText: 'popleft()$0' },
  { label: 'appendleft', kind: 'method', signature: 'deque.appendleft(x)', doc: 'Add an element to the left end of the deque', insertText: 'appendleft($0)' },
  { label: 'bisect_left', kind: 'function', signature: 'bisect.bisect_left(a, x)', doc: 'Return the leftmost insertion point for x that keeps the list sorted', insertText: 'bisect_left($1, $0)' },
  { label: 'bisect_right', kind: 'function', signature: 'bisect.bisect_right(a, x)', doc: 'Return the rightmost insertion point for x that keeps the list sorted', insertText: 'bisect_right($1, $0)' },
  { label: 'insort', kind: 'function', signature: 'bisect.insort(a, x)', doc: 'Insert x into a sorted list while keeping it sorted', insertText: 'insort($1, $0)' },
  { label: 'lru_cache', kind: 'function', signature: '@functools.lru_cache(maxsize=128)', doc: 'Decorator that caches a function\'s return values', insertText: 'lru_cache(maxsize=None)$0' },
  { label: 'cache', kind: 'function', signature: '@functools.cache', doc: 'Decorator that caches a function\'s return values with unlimited size', insertText: 'cache$0' },
  { label: 'inf', kind: 'constant', signature: 'math.inf', doc: 'Positive infinity as a float', insertText: 'inf' },
  { label: 'gcd', kind: 'function', signature: 'math.gcd(*integers)', doc: 'Return the greatest common divisor', insertText: 'gcd($0)' },
  { label: 'sqrt', kind: 'function', signature: 'math.sqrt(x)', doc: 'Return the square root', insertText: 'sqrt($0)' },
  { label: 'floor', kind: 'function', signature: 'math.floor(x)', doc: 'Round down to the nearest integer', insertText: 'floor($0)' },
  { label: 'ceil', kind: 'function', signature: 'math.ceil(x)', doc: 'Round up to the nearest integer', insertText: 'ceil($0)' },
  { label: 'permutations', kind: 'function', signature: 'itertools.permutations(iterable, r=None)', doc: 'Return all permutations', insertText: 'permutations($0)' },
  { label: 'combinations', kind: 'function', signature: 'itertools.combinations(iterable, r)', doc: 'Return all combinations', insertText: 'combinations($1, $0)' },
  { label: 'accumulate', kind: 'function', signature: 'itertools.accumulate(iterable, func=None)', doc: 'Return an iterator of accumulated results (sum by default)', insertText: 'accumulate($0)' },

  // ---- keywords ----
  { label: 'def', kind: 'keyword', signature: 'def name(args):', doc: 'Define a function', insertText: 'def ${1:name}(${2:args}):\n    $0' },
  { label: 'return', kind: 'keyword', signature: 'return expr', doc: 'Return a value from a function', insertText: 'return' },
  { label: 'if', kind: 'keyword', signature: 'if condition:', doc: 'Conditional branch', insertText: 'if ${1:condition}:\n    $0' },
  { label: 'elif', kind: 'keyword', signature: 'elif condition:', doc: 'Conditional branch (else if)', insertText: 'elif ${1:condition}:\n    $0' },
  { label: 'else', kind: 'keyword', signature: 'else:', doc: 'Default branch of a conditional', insertText: 'else:\n    $0' },
  { label: 'for', kind: 'keyword', signature: 'for item in iterable:', doc: 'Loop over an iterable', insertText: 'for ${1:item} in ${2:iterable}:\n    $0' },
  { label: 'while', kind: 'keyword', signature: 'while condition:', doc: 'Conditional loop', insertText: 'while ${1:condition}:\n    $0' },
  { label: 'in', kind: 'keyword', signature: 'x in iterable', doc: 'Membership/iteration test', insertText: 'in' },
  { label: 'not', kind: 'keyword', signature: 'not x', doc: 'Logical NOT', insertText: 'not' },
  { label: 'and', kind: 'keyword', signature: 'a and b', doc: 'Logical AND', insertText: 'and' },
  { label: 'or', kind: 'keyword', signature: 'a or b', doc: 'Logical OR', insertText: 'or' },
  { label: 'lambda', kind: 'keyword', signature: 'lambda args: expr', doc: 'Anonymous function', insertText: 'lambda $1: $0' },
  { label: 'yield', kind: 'keyword', signature: 'yield expr', doc: 'Yield a value from a generator', insertText: 'yield' },
  { label: 'class', kind: 'keyword', signature: 'class Name:', doc: 'Define a class', insertText: 'class ${1:Name}:\n    $0' },
  { label: 'import', kind: 'keyword', signature: 'import module', doc: 'Import a module', insertText: 'import' },
  { label: 'from', kind: 'keyword', signature: 'from module import name', doc: 'Import specific members from a module', insertText: 'from' },
  { label: 'None', kind: 'keyword', signature: 'None', doc: 'The null value constant', insertText: 'None' },
  { label: 'True', kind: 'keyword', signature: 'True', doc: 'Boolean true value', insertText: 'True' },
  { label: 'False', kind: 'keyword', signature: 'False', doc: 'Boolean false value', insertText: 'False' },
  { label: 'break', kind: 'keyword', signature: 'break', doc: 'Break out of the current loop', insertText: 'break' },
  { label: 'continue', kind: 'keyword', signature: 'continue', doc: 'Skip the rest of the current loop iteration', insertText: 'continue' },
  { label: 'global', kind: 'keyword', signature: 'global name', doc: 'Declare a name as referring to a global variable', insertText: 'global' },
  { label: 'nonlocal', kind: 'keyword', signature: 'nonlocal name', doc: 'Declare a name as referring to a variable in an enclosing scope', insertText: 'nonlocal' },
  { label: 'try', kind: 'keyword', signature: 'try:', doc: 'Exception-handling block', insertText: 'try:\n    $0' },
  { label: 'except', kind: 'keyword', signature: 'except Exception as e:', doc: 'Catch and handle an exception', insertText: 'except ${1:Exception} as ${2:e}:\n    $0' },
];
