import type { DictEntry } from './types';

export const python: DictEntry[] = [
  // ---- list 方法 ----
  { label: 'append', kind: 'method', signature: 'list.append(x)', doc: '在列表末尾添加一个元素', insertText: 'append($0)' },
  { label: 'pop', kind: 'method', signature: 'list.pop(i=-1)', doc: '删除并返回指定位置的元素，默认最后一个', insertText: 'pop($0)' },
  { label: 'sort', kind: 'method', signature: 'list.sort(key=None, reverse=False)', doc: '原地对列表排序', insertText: 'sort($0)' },
  { label: 'sorted', kind: 'function', signature: 'sorted(iterable, key=None, reverse=False)', doc: '返回排序后的新列表', insertText: 'sorted($0)' },
  { label: 'reverse', kind: 'method', signature: 'list.reverse()', doc: '原地反转列表', insertText: 'reverse()$0' },
  { label: 'insert', kind: 'method', signature: 'list.insert(i, x)', doc: '在指定位置插入元素', insertText: 'insert($1, $0)' },
  { label: 'remove', kind: 'method', signature: 'list.remove(x)', doc: '删除第一个等于 x 的元素', insertText: 'remove($0)' },
  { label: 'index', kind: 'method', signature: 'list.index(x)', doc: '返回 x 第一次出现的下标，找不到抛异常', insertText: 'index($0)' },
  { label: 'count', kind: 'method', signature: 'list.count(x)', doc: '统计 x 出现的次数（list/str 通用）', insertText: 'count($0)' },

  // ---- str 方法 ----
  { label: 'join', kind: 'method', signature: 'sep.join(iterable)', doc: '用分隔符拼接字符串序列', insertText: 'join($0)' },
  { label: 'split', kind: 'method', signature: 'str.split(sep=None)', doc: '按分隔符切分字符串为列表', insertText: 'split($0)' },
  { label: 'strip', kind: 'method', signature: 'str.strip(chars=None)', doc: '去除首尾空白（或指定字符）', insertText: 'strip()$0' },
  { label: 'lower', kind: 'method', signature: 'str.lower()', doc: '转换为小写', insertText: 'lower()$0' },
  { label: 'upper', kind: 'method', signature: 'str.upper()', doc: '转换为大写', insertText: 'upper()$0' },
  { label: 'startswith', kind: 'method', signature: 'str.startswith(prefix)', doc: '判断字符串是否以 prefix 开头', insertText: 'startswith($0)' },
  { label: 'endswith', kind: 'method', signature: 'str.endswith(suffix)', doc: '判断字符串是否以 suffix 结尾', insertText: 'endswith($0)' },
  { label: 'replace', kind: 'method', signature: 'str.replace(old, new)', doc: '替换字符串中所有 old 为 new', insertText: 'replace($1, $0)' },
  { label: 'find', kind: 'method', signature: 'str.find(sub)', doc: '返回子串首次出现的下标，找不到返回 -1', insertText: 'find($0)' },
  { label: 'isdigit', kind: 'method', signature: 'str.isdigit()', doc: '判断字符串是否全为数字字符', insertText: 'isdigit()$0' },
  { label: 'isalpha', kind: 'method', signature: 'str.isalpha()', doc: '判断字符串是否全为字母', insertText: 'isalpha()$0' },
  { label: 'ord', kind: 'function', signature: 'ord(c)', doc: '返回单字符对应的 Unicode 码点', insertText: 'ord($0)' },
  { label: 'chr', kind: 'function', signature: 'chr(i)', doc: '返回码点 i 对应的字符', insertText: 'chr($0)' },

  // ---- dict/set 方法 ----
  { label: 'get', kind: 'method', signature: 'dict.get(key, default=None)', doc: '按键取值，不存在时返回 default', insertText: 'get($0)' },
  { label: 'keys', kind: 'method', signature: 'dict.keys()', doc: '返回字典所有键的视图', insertText: 'keys()$0' },
  { label: 'values', kind: 'method', signature: 'dict.values()', doc: '返回字典所有值的视图', insertText: 'values()$0' },
  { label: 'items', kind: 'method', signature: 'dict.items()', doc: '返回字典所有键值对的视图', insertText: 'items()$0' },
  { label: 'setdefault', kind: 'method', signature: 'dict.setdefault(key, default=None)', doc: '键存在则返回其值，否则设为 default 并返回', insertText: 'setdefault($1, $0)' },
  { label: 'add', kind: 'method', signature: 'set.add(x)', doc: '向集合添加元素', insertText: 'add($0)' },
  { label: 'discard', kind: 'method', signature: 'set.discard(x)', doc: '从集合中移除元素，不存在也不报错', insertText: 'discard($0)' },
  { label: 'update', kind: 'method', signature: 'set.update(iterable)', doc: '用可迭代对象更新集合（或字典）', insertText: 'update($0)' },

  // ---- builtins ----
  { label: 'len', kind: 'function', signature: 'len(obj)', doc: '返回对象的长度', insertText: 'len($0)' },
  { label: 'range', kind: 'function', signature: 'range(start, stop, step=1)', doc: '生成整数序列', insertText: 'range($0)' },
  { label: 'enumerate', kind: 'function', signature: 'enumerate(iterable, start=0)', doc: '返回带下标的迭代器', insertText: 'enumerate($0)' },
  { label: 'zip', kind: 'function', signature: 'zip(*iterables)', doc: '并行打包多个可迭代对象', insertText: 'zip($0)' },
  { label: 'map', kind: 'function', signature: 'map(func, iterable)', doc: '对可迭代对象逐个应用函数', insertText: 'map($1, $0)' },
  { label: 'filter', kind: 'function', signature: 'filter(func, iterable)', doc: '过滤出使函数返回真值的元素', insertText: 'filter($1, $0)' },
  { label: 'sum', kind: 'function', signature: 'sum(iterable, start=0)', doc: '求和', insertText: 'sum($0)' },
  { label: 'min', kind: 'function', signature: 'min(iterable)', doc: '返回最小值', insertText: 'min($0)' },
  { label: 'max', kind: 'function', signature: 'max(iterable)', doc: '返回最大值', insertText: 'max($0)' },
  { label: 'abs', kind: 'function', signature: 'abs(x)', doc: '返回绝对值', insertText: 'abs($0)' },
  { label: 'all', kind: 'function', signature: 'all(iterable)', doc: '所有元素都为真则返回 True', insertText: 'all($0)' },
  { label: 'any', kind: 'function', signature: 'any(iterable)', doc: '任一元素为真则返回 True', insertText: 'any($0)' },
  { label: 'set', kind: 'class', signature: 'set(iterable=())', doc: '创建集合', insertText: 'set($0)' },
  { label: 'dict', kind: 'class', signature: 'dict(**kwargs)', doc: '创建字典', insertText: 'dict($0)' },
  { label: 'list', kind: 'class', signature: 'list(iterable=())', doc: '创建列表', insertText: 'list($0)' },
  { label: 'tuple', kind: 'class', signature: 'tuple(iterable=())', doc: '创建元组', insertText: 'tuple($0)' },
  { label: 'str', kind: 'class', signature: 'str(object=\'\')', doc: '转换为字符串', insertText: 'str($0)' },
  { label: 'int', kind: 'class', signature: 'int(x=0, base=10)', doc: '转换为整数', insertText: 'int($0)' },
  { label: 'float', kind: 'class', signature: 'float(x=0.0)', doc: '转换为浮点数', insertText: 'float($0)' },
  { label: 'bool', kind: 'class', signature: 'bool(x=False)', doc: '转换为布尔值', insertText: 'bool($0)' },
  { label: 'print', kind: 'function', signature: 'print(*objects, sep=\' \', end=\'\\n\')', doc: '打印输出', insertText: 'print($0)' },
  { label: 'reversed', kind: 'function', signature: 'reversed(sequence)', doc: '返回反向迭代器', insertText: 'reversed($0)' },
  { label: 'isinstance', kind: 'function', signature: 'isinstance(obj, classinfo)', doc: '判断对象是否为指定类型的实例', insertText: 'isinstance($1, $0)' },
  { label: 'divmod', kind: 'function', signature: 'divmod(a, b)', doc: '同时返回商和余数的元组', insertText: 'divmod($1, $0)' },
  { label: 'pow', kind: 'function', signature: 'pow(base, exp, mod=None)', doc: '计算幂（可选取模）', insertText: 'pow($1, $0)' },
  { label: 'round', kind: 'function', signature: 'round(number, ndigits=None)', doc: '四舍五入到指定精度', insertText: 'round($0)' },

  // ---- 模块 ----
  { label: 'heapq', kind: 'module', signature: 'import heapq', doc: '堆队列（最小堆）算法模块', insertText: 'heapq' },
  { label: 'heappush', kind: 'function', signature: 'heapq.heappush(heap, item)', doc: '向最小堆压入元素', insertText: 'heappush($1, $0)' },
  { label: 'heappop', kind: 'function', signature: 'heapq.heappop(heap)', doc: '弹出并返回堆中最小元素', insertText: 'heappop($0)' },
  { label: 'heapify', kind: 'function', signature: 'heapq.heapify(x)', doc: '原地将列表转换为堆', insertText: 'heapify($0)' },
  { label: 'Counter', kind: 'class', signature: 'collections.Counter(iterable)', doc: '计数器字典，统计元素出现次数', insertText: 'Counter($0)' },
  { label: 'defaultdict', kind: 'class', signature: 'collections.defaultdict(default_factory)', doc: '带默认值工厂的字典', insertText: 'defaultdict($0)' },
  { label: 'deque', kind: 'class', signature: 'collections.deque(iterable=())', doc: '双端队列', insertText: 'deque($0)' },
  { label: 'popleft', kind: 'method', signature: 'deque.popleft()', doc: '弹出并返回双端队列左端元素', insertText: 'popleft()$0' },
  { label: 'appendleft', kind: 'method', signature: 'deque.appendleft(x)', doc: '在双端队列左端添加元素', insertText: 'appendleft($0)' },
  { label: 'bisect_left', kind: 'function', signature: 'bisect.bisect_left(a, x)', doc: '返回 x 可插入的最左位置，保持有序', insertText: 'bisect_left($1, $0)' },
  { label: 'bisect_right', kind: 'function', signature: 'bisect.bisect_right(a, x)', doc: '返回 x 可插入的最右位置，保持有序', insertText: 'bisect_right($1, $0)' },
  { label: 'insort', kind: 'function', signature: 'bisect.insort(a, x)', doc: '将 x 插入有序列表并保持有序', insertText: 'insort($1, $0)' },
  { label: 'lru_cache', kind: 'function', signature: '@functools.lru_cache(maxsize=128)', doc: '函数结果缓存装饰器', insertText: 'lru_cache(maxsize=None)$0' },
  { label: 'cache', kind: 'function', signature: '@functools.cache', doc: '无限容量的函数结果缓存装饰器', insertText: 'cache$0' },
  { label: 'inf', kind: 'constant', signature: 'math.inf', doc: '正无穷大浮点数', insertText: 'inf' },
  { label: 'gcd', kind: 'function', signature: 'math.gcd(*integers)', doc: '返回最大公约数', insertText: 'gcd($0)' },
  { label: 'sqrt', kind: 'function', signature: 'math.sqrt(x)', doc: '返回平方根', insertText: 'sqrt($0)' },
  { label: 'floor', kind: 'function', signature: 'math.floor(x)', doc: '向下取整', insertText: 'floor($0)' },
  { label: 'ceil', kind: 'function', signature: 'math.ceil(x)', doc: '向上取整', insertText: 'ceil($0)' },
  { label: 'permutations', kind: 'function', signature: 'itertools.permutations(iterable, r=None)', doc: '返回所有排列', insertText: 'permutations($0)' },
  { label: 'combinations', kind: 'function', signature: 'itertools.combinations(iterable, r)', doc: '返回所有组合', insertText: 'combinations($1, $0)' },
  { label: 'accumulate', kind: 'function', signature: 'itertools.accumulate(iterable, func=None)', doc: '返回累积结果的迭代器（默认累加）', insertText: 'accumulate($0)' },

  // ---- 关键字 ----
  { label: 'def', kind: 'keyword', signature: 'def name(args):', doc: '定义函数', insertText: 'def ${1:name}(${2:args}):\n    $0' },
  { label: 'return', kind: 'keyword', signature: 'return expr', doc: '从函数返回值', insertText: 'return' },
  { label: 'if', kind: 'keyword', signature: 'if condition:', doc: '条件分支', insertText: 'if ${1:condition}:\n    $0' },
  { label: 'elif', kind: 'keyword', signature: 'elif condition:', doc: '条件分支（else if）', insertText: 'elif ${1:condition}:\n    $0' },
  { label: 'else', kind: 'keyword', signature: 'else:', doc: '条件分支的默认分支', insertText: 'else:\n    $0' },
  { label: 'for', kind: 'keyword', signature: 'for item in iterable:', doc: '遍历循环', insertText: 'for ${1:item} in ${2:iterable}:\n    $0' },
  { label: 'while', kind: 'keyword', signature: 'while condition:', doc: '条件循环', insertText: 'while ${1:condition}:\n    $0' },
  { label: 'in', kind: 'keyword', signature: 'x in iterable', doc: '成员/迭代关系判断', insertText: 'in' },
  { label: 'not', kind: 'keyword', signature: 'not x', doc: '逻辑非', insertText: 'not' },
  { label: 'and', kind: 'keyword', signature: 'a and b', doc: '逻辑与', insertText: 'and' },
  { label: 'or', kind: 'keyword', signature: 'a or b', doc: '逻辑或', insertText: 'or' },
  { label: 'lambda', kind: 'keyword', signature: 'lambda args: expr', doc: '匿名函数', insertText: 'lambda $1: $0' },
  { label: 'yield', kind: 'keyword', signature: 'yield expr', doc: '生成器返回值', insertText: 'yield' },
  { label: 'class', kind: 'keyword', signature: 'class Name:', doc: '定义类', insertText: 'class ${1:Name}:\n    $0' },
  { label: 'import', kind: 'keyword', signature: 'import module', doc: '导入模块', insertText: 'import' },
  { label: 'from', kind: 'keyword', signature: 'from module import name', doc: '从模块导入指定成员', insertText: 'from' },
  { label: 'None', kind: 'keyword', signature: 'None', doc: '空值常量', insertText: 'None' },
  { label: 'True', kind: 'keyword', signature: 'True', doc: '布尔真值', insertText: 'True' },
  { label: 'False', kind: 'keyword', signature: 'False', doc: '布尔假值', insertText: 'False' },
  { label: 'break', kind: 'keyword', signature: 'break', doc: '跳出当前循环', insertText: 'break' },
  { label: 'continue', kind: 'keyword', signature: 'continue', doc: '跳过本次循环剩余部分', insertText: 'continue' },
  { label: 'global', kind: 'keyword', signature: 'global name', doc: '声明使用全局变量', insertText: 'global' },
  { label: 'nonlocal', kind: 'keyword', signature: 'nonlocal name', doc: '声明使用外层函数作用域变量', insertText: 'nonlocal' },
  { label: 'try', kind: 'keyword', signature: 'try:', doc: '异常捕获块', insertText: 'try:\n    $0' },
  { label: 'except', kind: 'keyword', signature: 'except Exception as e:', doc: '捕获并处理异常', insertText: 'except ${1:Exception} as ${2:e}:\n    $0' },
];
