/* global process, console */
// Shared emitter for gen-dicts: converts <lang>.raw.json extractor output
// into committed lib/dicts/generated/<lang>.ts DictEntry[] modules.
// Usage: node scripts/gen-dicts/emit.mjs <dir-containing-*.raw.json>
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const KINDS = new Set(['method', 'function', 'keyword', 'module', 'class', 'snippet', 'constant']);

const LANGS = {
  java: { file: 'java.ts', exportName: 'javaGenerated' },
  python: { file: 'python.ts', exportName: 'pythonGenerated' },
  javascript: { file: 'javascript.ts', exportName: 'javascriptGenerated' },
  go: { file: 'go.ts', exportName: 'goGenerated' },
};

export function validate(entries) {
  const errors = [];
  entries.forEach((e, i) => {
    if (!e.label) errors.push(`entry ${i}: empty label`);
    if (!KINDS.has(e.kind)) errors.push(`entry ${i} (${e.label}): bad kind "${e.kind}"`);
    if (!e.signature) errors.push(`entry ${i} (${e.label}): empty signature`);
  });
  return errors;
}

export function deriveInsertText(e) {
  if (e.insertText) return e.insertText;
  if (e.kind === 'method' || e.kind === 'function') {
    const n = e.arity ?? 1;
    if (n <= 0) return `${e.label}()$0`;
    if (n === 1) return `${e.label}($0)`;
    const stops = [];
    for (let i = 1; i < n; i++) stops.push(`$${i}`);
    stops.push('$0');
    return `${e.label}(${stops.join(', ')})`;
  }
  return e.label;
}

const short = (c) => c.split(/[./]/).pop();

export function dedupe(entries) {
  const byKey = new Map();
  for (const e of entries) {
    const key = `${e.label}|${e.kind}`;
    const prev = byKey.get(key);
    if (!prev) {
      byKey.set(key, { ...e, containers: e.container ? [e.container] : [] });
      continue;
    }
    if (e.container && !prev.containers.includes(e.container)) prev.containers.push(e.container);
    // Keep the lowest-arity overload so the popup shows the simplest form.
    if ((e.arity ?? 1) < (prev.arity ?? 1)) {
      prev.arity = e.arity;
      prev.signature = e.signature;
    }
    if (!prev.doc && e.doc) prev.doc = e.doc;
  }
  return [...byKey.values()].map(({ containers, ...e }) => {
    const doc = e.doc || e.signature;
    return {
      ...e,
      doc: containers.length > 1 ? `${doc} (on ${containers.map(short).join('/')})` : doc,
    };
  });
}

const KIND_ORDER = ['class', 'method', 'function', 'constant', 'module', 'keyword', 'snippet'];

export function renderModule(exportName, entries) {
  const sorted = [...entries].sort(
    (a, b) => KIND_ORDER.indexOf(a.kind) - KIND_ORDER.indexOf(b.kind) || a.label.localeCompare(b.label),
  );
  const s = (v) => JSON.stringify(v);
  const lines = sorted.map(
    (e) =>
      `  { label: ${s(e.label)}, kind: ${s(e.kind)}, signature: ${s(e.signature)}, doc: ${s(e.doc)}, insertText: ${s(deriveInsertText(e))} },`,
  );
  return [
    '// GENERATED by scripts/gen-dicts — do not edit. Regenerate with: npm run gen:dicts',
    "import type { DictEntry } from '../types';",
    '',
    `export const ${exportName}: DictEntry[] = [`,
    ...lines,
    '];',
    '',
  ].join('\n');
}

function main() {
  const rawDir = process.argv[2];
  if (!rawDir) {
    console.error('usage: node emit.mjs <raw-json-dir>');
    process.exit(1);
  }
  const outDir = path.join('lib', 'dicts', 'generated');
  fs.mkdirSync(outDir, { recursive: true });
  let wrote = 0;
  for (const f of fs.readdirSync(rawDir).filter((n) => n.endsWith('.raw.json'))) {
    const raw = JSON.parse(fs.readFileSync(path.join(rawDir, f), 'utf8'));
    const lang = LANGS[raw.language];
    if (!lang) {
      console.error(`unknown language "${raw.language}" in ${f}`);
      process.exit(1);
    }
    const errors = validate(raw.entries);
    if (errors.length) {
      console.error(`${f}:\n  ${errors.join('\n  ')}`);
      process.exit(1);
    }
    const entries = dedupe(raw.entries);
    fs.writeFileSync(path.join(outDir, lang.file), renderModule(lang.exportName, entries));
    console.log(`wrote ${path.join(outDir, lang.file)} (${entries.length} entries)`);
    wrote++;
  }
  if (!wrote) {
    console.error(`no *.raw.json files found in ${rawDir}`);
    process.exit(1);
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
