import { expect, test } from 'vitest';
// Plain-JS ESM module; no type declarations on purpose.
// @ts-expect-error untyped .mjs import
import { deriveInsertText, dedupe, validate, renderModule } from '../scripts/gen-dicts/emit.mjs';

test('deriveInsertText derives from arity for callables', () => {
  expect(deriveInsertText({ label: 'peek', kind: 'method', arity: 0 })).toBe('peek()$0');
  expect(deriveInsertText({ label: 'charAt', kind: 'method', arity: 1 })).toBe('charAt($0)');
  expect(deriveInsertText({ label: 'merge', kind: 'function', arity: 3 })).toBe('merge($1, $2, $0)');
  // missing arity defaults to 1
  expect(deriveInsertText({ label: 'find', kind: 'method' })).toBe('find($0)');
});

test('deriveInsertText respects explicit insertText and non-callable kinds', () => {
  expect(deriveInsertText({ label: 'ArrayDeque', kind: 'class', insertText: 'ArrayDeque<$0>' })).toBe('ArrayDeque<$0>');
  expect(deriveInsertText({ label: 'break', kind: 'keyword' })).toBe('break');
  expect(deriveInsertText({ label: 'inf', kind: 'constant' })).toBe('inf');
});

test('dedupe merges duplicate label|kind, keeps lowest arity, notes containers', () => {
  const out = dedupe([
    { label: 'addFirst', kind: 'method', container: 'java.util.Deque', signature: 'deque.addFirst(a)', doc: 'Add to head', arity: 1 },
    { label: 'addFirst', kind: 'method', container: 'java.util.ArrayDeque', signature: 'deque.addFirst(a)', doc: '', arity: 1 },
    { label: 'sort', kind: 'function', container: 'java.util.Arrays', signature: 'Arrays.sort(a, b, c)', doc: 'Sort a range', arity: 3 },
    { label: 'sort', kind: 'function', container: 'java.util.Arrays', signature: 'Arrays.sort(a)', doc: 'Sort an array', arity: 1 },
  ]);
  expect(out).toHaveLength(2);
  const addFirst = out.find((e: { label: string }) => e.label === 'addFirst');
  expect(addFirst.doc).toBe('Add to head (on Deque/ArrayDeque)');
  const sort = out.find((e: { label: string }) => e.label === 'sort');
  expect(sort.signature).toBe('Arrays.sort(a)');
});

test('dedupe falls back to signature when doc is empty', () => {
  const out = dedupe([{ label: 'x', kind: 'method', signature: 'a.x()', doc: '', arity: 0 }]);
  expect(out[0].doc).toBe('a.x()');
});

test('validate reports bad entries', () => {
  expect(validate([{ label: 'ok', kind: 'method', signature: 's', doc: '' }])).toEqual([]);
  expect(validate([{ label: '', kind: 'method', signature: 's', doc: '' }]).length).toBeGreaterThan(0);
  expect(validate([{ label: 'x', kind: 'bogus', signature: 's', doc: '' }]).length).toBeGreaterThan(0);
  expect(validate([{ label: 'x', kind: 'method', signature: '', doc: '' }]).length).toBeGreaterThan(0);
});

test('renderModule emits a sorted, typed TS module with header', () => {
  const src = renderModule('javaGenerated', [
    { label: 'poll', kind: 'method', signature: 'q.poll()', doc: 'Poll', arity: 0 },
    { label: 'ArrayDeque', kind: 'class', signature: 'ArrayDeque<E>', doc: 'A deque', insertText: 'ArrayDeque<$0>' },
  ]);
  expect(src).toContain('// GENERATED by scripts/gen-dicts');
  expect(src).toContain("import type { DictEntry } from '../types';");
  expect(src).toContain('export const javaGenerated: DictEntry[] = [');
  // class sorts before method
  expect(src.indexOf('"ArrayDeque"')).toBeLessThan(src.indexOf('"poll"'));
  // insertText derived from arity during render
  expect(src).toContain('"poll()$0"');
});
